### ISSUE TITLE
Trusted certificate of SSL maven repository

### ISSUE THREAD

**Issue by alexsantos** [ecsec/open-ecard#11]
I tried to do ```mvn clean install``` but maven complained about the PKI  - Unable to find valid certification path to requested target

I had to export the certificate from https://mvn.ecsec.de/ and then import it to the cacert file from the JRE.

**Comment by sake** [comment]
That's a known problem and there is no fix we can provide as the truststore is part of the Java VM. In the future we will try to move the app into some official maven repository.
